#!/bin/bash

# accmanager post nom prenom account risk


URL_API="https://resolute-planet-344619.oa.r.appspot.com/acc"

usage(){
echo "Usage :"
echo "${0##.*/} [post|get|delete] OPTIONS..."
echo "Options post : NOM PRENOM RISK [ACCOUNT] # le risk est 0 ou 1"
echo "Options get : [all]"
echo "Options delete : [ID || NOM]"
}


post(){
	if [ "$#" -eq 0 ]
	then
		usage
		exit 2
	fi
	if [ "$#" -lt 3 ]
	then
		echo "il manque des variables obligatoires"
		usage
		exit 3
	fi

	risk="$3"
	if [ "$risk" != "1" ] # && [ "$risk" != "0" ]
	then
		risk=0
	fi

	account="$4"
	if [ -z "$account" ]
	then
		account="0.0"
	fi

	jsonData="{\"nom\":\"$1\",\"prenom\":\"$2\",\"risk\":$risk,\"account\":$account}"
	
	echo "$jsonData"
	curl -X POST ${URL_API} -d "$jsonData" -H "Content-Type: application/json"
}

get(){
	if [ "$#" -eq 0 ]
	then
		curl "${URL_API}"
	fi
}

delete(){
	if [ "$#" -eq 0 ]
	then
		usage
		exit 2
	fi

	if [ "$1" != "all" ]
	then
		status_code=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE "${URL_API}/$1")
		echo "status code de retour est $status_code"
	fi
}

if [ "$#" -eq 0 ]
then
	usage
	exit 1
fi

case "$1" in
	"post")
		shift
		post "$@"
		;;
	"delete")
		shift
		delete "$@"
		;;
	"get")
		shift
		get "$@"
		;;
	*)
		usage
		exit 1
		;;
esac
