#!/bin/bash

# accmanager post nom prenom account risk


URL_API="https://resolute-planet-344619.oa.r.appspot.com/acc"
# URL_API="http://localhost:8080/acc"

usage(){
cat <<EOF 
Usage : ${0##.*/} [post|get|delete|add] VALUES...

VALUES 	post : NOM PRENOM RISK [ACCOUNT]
	get : [ID]
	delete : ID|NOM
	add ID ACCOUNT_TO_ADD
EOF
}


post(){
	if [ "$#" -eq 0 ]
	then
		usage
		exit 2
	fi
	if [ "$#" -lt 3 ]
	then
		echo "il manque des variables obligatoires"
		usage
		exit 3
	fi

	risk="$3"
	if [ "$risk" != "1" ] # && [ "$risk" != "0" ]
	then
		risk=0
	fi

	account="$4"
	if [ -z "$account" ]
	then
		account="0.0"
	fi

	jsonData="{\"nom\":\"$1\",\"prenom\":\"$2\",\"risk\":$risk,\"account\":$account}"
	
	echo "$jsonData"
	status_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${URL_API} -d "$jsonData" -H "Content-Type: application/json")

	echo "status code de la response : $status_code"
}

get() {
	curl "${URL_API}/$1" 
}

delete(){
	if [ "$#" -eq 0 ]
	then
		usage
		exit 2
	fi

	if [ "$1" != "all" ]
	then
		status_code=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE "${URL_API}/$1")
		echo "status code de retour est $status_code"
	fi
}

updateAddAccount() {
	if [ "$#" -lt 2 ]
	then
		usage
		exit 2
	fi

	curl -X PUT "${URL_API}/add/$1?accountToAdd=$2"
}

if [ "$#" -eq 0 ]
then
	usage
	exit 1
fi

case "$1" in
	"post")
		shift
		post "$@"
		;;
	"delete")
		shift
		delete "$@"
		;;
	"get")
		shift
		get "$@"
		;;
	"add")
		shift
		updateAddAccount "$@"
		;;
	*)
		usage
		exit 1
		;;
esac
